[theme]
primaryColor = "#6C63FF"
backgroundColor = "#FFF3D7"
secondaryBackgroundColor = "#FFE8B8"
textColor = "#333333"
font = "serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 